// Generated by gencpp from file taobot_link/Odom.msg
// DO NOT EDIT!


#ifndef TAOBOT_LINK_MESSAGE_ODOM_H
#define TAOBOT_LINK_MESSAGE_ODOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace taobot_link
{
template <class ContainerAllocator>
struct Odom_
{
  typedef Odom_<ContainerAllocator> Type;

  Odom_()
    : x_pos(0.0)
    , y_pos(0.0)
    , theta(0.0)  {
    }
  Odom_(const ContainerAllocator& _alloc)
    : x_pos(0.0)
    , y_pos(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef float _x_pos_type;
  _x_pos_type x_pos;

   typedef float _y_pos_type;
  _y_pos_type y_pos;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::taobot_link::Odom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::taobot_link::Odom_<ContainerAllocator> const> ConstPtr;

}; // struct Odom_

typedef ::taobot_link::Odom_<std::allocator<void> > Odom;

typedef boost::shared_ptr< ::taobot_link::Odom > OdomPtr;
typedef boost::shared_ptr< ::taobot_link::Odom const> OdomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::taobot_link::Odom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::taobot_link::Odom_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace taobot_link

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'taobot_link': ['/home/eee/lingfei_ws/agv/src/taobot_link/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::taobot_link::Odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::taobot_link::Odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taobot_link::Odom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::taobot_link::Odom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taobot_link::Odom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::taobot_link::Odom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::taobot_link::Odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9518dd7f72bb88584af16172a7ace5f";
  }

  static const char* value(const ::taobot_link::Odom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9518dd7f72bb885ULL;
  static const uint64_t static_value2 = 0x84af16172a7ace5fULL;
};

template<class ContainerAllocator>
struct DataType< ::taobot_link::Odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "taobot_link/Odom";
  }

  static const char* value(const ::taobot_link::Odom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::taobot_link::Odom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x_pos\n\
float32 y_pos\n\
float32 theta\n\
";
  }

  static const char* value(const ::taobot_link::Odom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::taobot_link::Odom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_pos);
      stream.next(m.y_pos);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Odom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::taobot_link::Odom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::taobot_link::Odom_<ContainerAllocator>& v)
  {
    s << indent << "x_pos: ";
    Printer<float>::stream(s, indent + "  ", v.x_pos);
    s << indent << "y_pos: ";
    Printer<float>::stream(s, indent + "  ", v.y_pos);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAOBOT_LINK_MESSAGE_ODOM_H
