# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vicon_xb/viconPoseMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class viconPoseMsg(genpy.Message):
  _md5sum = "f87f226dd5b11ef67fbde47b43eb429e"
  _type = "vicon_xb/viconPoseMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time time_stamp
float32 x
float32 y
float32 z
float32 dx
float32 dy
float32 dz
float32 roll
float32 pitch
float32 yaw
"""
  __slots__ = ['time_stamp','x','y','z','dx','dy','dz','roll','pitch','yaw']
  _slot_types = ['time','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time_stamp,x,y,z,dx,dy,dz,roll,pitch,yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(viconPoseMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.dx is None:
        self.dx = 0.
      if self.dy is None:
        self.dy = 0.
      if self.dz is None:
        self.dz = 0.
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
    else:
      self.time_stamp = genpy.Time()
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.dx = 0.
      self.dy = 0.
      self.dz = 0.
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I9f().pack(_x.time_stamp.secs, _x.time_stamp.nsecs, _x.x, _x.y, _x.z, _x.dx, _x.dy, _x.dz, _x.roll, _x.pitch, _x.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 44
      (_x.time_stamp.secs, _x.time_stamp.nsecs, _x.x, _x.y, _x.z, _x.dx, _x.dy, _x.dz, _x.roll, _x.pitch, _x.yaw,) = _get_struct_2I9f().unpack(str[start:end])
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I9f().pack(_x.time_stamp.secs, _x.time_stamp.nsecs, _x.x, _x.y, _x.z, _x.dx, _x.dy, _x.dz, _x.roll, _x.pitch, _x.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 44
      (_x.time_stamp.secs, _x.time_stamp.nsecs, _x.x, _x.y, _x.z, _x.dx, _x.dy, _x.dz, _x.roll, _x.pitch, _x.yaw,) = _get_struct_2I9f().unpack(str[start:end])
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I9f = None
def _get_struct_2I9f():
    global _struct_2I9f
    if _struct_2I9f is None:
        _struct_2I9f = struct.Struct("<2I9f")
    return _struct_2I9f
