// Generated by gencpp from file vicon_xb/viconXbSrv.msg
// DO NOT EDIT!


#ifndef VICON_XB_MESSAGE_VICONXBSRV_H
#define VICON_XB_MESSAGE_VICONXBSRV_H

#include <ros/service_traits.h>


#include <vicon_xb/viconXbSrvRequest.h>
#include <vicon_xb/viconXbSrvResponse.h>


namespace vicon_xb
{

struct viconXbSrv
{

typedef viconXbSrvRequest Request;
typedef viconXbSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct viconXbSrv
} // namespace vicon_xb


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vicon_xb::viconXbSrv > {
  static const char* value()
  {
    return "690ec01b63ec02305afae8d102907248";
  }

  static const char* value(const ::vicon_xb::viconXbSrv&) { return value(); }
};

template<>
struct DataType< ::vicon_xb::viconXbSrv > {
  static const char* value()
  {
    return "vicon_xb/viconXbSrv";
  }

  static const char* value(const ::vicon_xb::viconXbSrv&) { return value(); }
};


// service_traits::MD5Sum< ::vicon_xb::viconXbSrvRequest> should match 
// service_traits::MD5Sum< ::vicon_xb::viconXbSrv > 
template<>
struct MD5Sum< ::vicon_xb::viconXbSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vicon_xb::viconXbSrv >::value();
  }
  static const char* value(const ::vicon_xb::viconXbSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vicon_xb::viconXbSrvRequest> should match 
// service_traits::DataType< ::vicon_xb::viconXbSrv > 
template<>
struct DataType< ::vicon_xb::viconXbSrvRequest>
{
  static const char* value()
  {
    return DataType< ::vicon_xb::viconXbSrv >::value();
  }
  static const char* value(const ::vicon_xb::viconXbSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vicon_xb::viconXbSrvResponse> should match 
// service_traits::MD5Sum< ::vicon_xb::viconXbSrv > 
template<>
struct MD5Sum< ::vicon_xb::viconXbSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vicon_xb::viconXbSrv >::value();
  }
  static const char* value(const ::vicon_xb::viconXbSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vicon_xb::viconXbSrvResponse> should match 
// service_traits::DataType< ::vicon_xb::viconXbSrv > 
template<>
struct DataType< ::vicon_xb::viconXbSrvResponse>
{
  static const char* value()
  {
    return DataType< ::vicon_xb::viconXbSrv >::value();
  }
  static const char* value(const ::vicon_xb::viconXbSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VICON_XB_MESSAGE_VICONXBSRV_H
