// Generated by gencpp from file vicon_xb/viconXbSrvRequest.msg
// DO NOT EDIT!


#ifndef VICON_XB_MESSAGE_VICONXBSRVREQUEST_H
#define VICON_XB_MESSAGE_VICONXBSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vicon_xb
{
template <class ContainerAllocator>
struct viconXbSrvRequest_
{
  typedef viconXbSrvRequest_<ContainerAllocator> Type;

  viconXbSrvRequest_()
    : block(false)
    , logfile_idx(0)  {
    }
  viconXbSrvRequest_(const ContainerAllocator& _alloc)
    : block(false)
    , logfile_idx(0)  {
  (void)_alloc;
    }



   typedef uint8_t _block_type;
  _block_type block;

   typedef int32_t _logfile_idx_type;
  _logfile_idx_type logfile_idx;




  typedef boost::shared_ptr< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct viconXbSrvRequest_

typedef ::vicon_xb::viconXbSrvRequest_<std::allocator<void> > viconXbSrvRequest;

typedef boost::shared_ptr< ::vicon_xb::viconXbSrvRequest > viconXbSrvRequestPtr;
typedef boost::shared_ptr< ::vicon_xb::viconXbSrvRequest const> viconXbSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vicon_xb

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'vicon_xb': ['/home/eee/lingfei_ws/agv/src/vicon_xb/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed681b93b567be83d5e7ee5788d064f3";
  }

  static const char* value(const ::vicon_xb::viconXbSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed681b93b567be83ULL;
  static const uint64_t static_value2 = 0xd5e7ee5788d064f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vicon_xb/viconXbSrvRequest";
  }

  static const char* value(const ::vicon_xb::viconXbSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool block\n\
int32 logfile_idx\n\
";
  }

  static const char* value(const ::vicon_xb::viconXbSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.block);
      stream.next(m.logfile_idx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct viconXbSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vicon_xb::viconXbSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vicon_xb::viconXbSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "block: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block);
    s << indent << "logfile_idx: ";
    Printer<int32_t>::stream(s, indent + "  ", v.logfile_idx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VICON_XB_MESSAGE_VICONXBSRVREQUEST_H
